[package]
name = "workos-plugin-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
workos-storage = { workspace = true }
workos-permission = { workspace = true }
workos-manual = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
zip = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tempfile = "3"
